### ISSUE TITLE
Set dynamic values on headers in message_properties

### ISSUE THREAD

**Issue by gkoudjou** [logstash-plugins/logstash-integration-rabbitmq#27]
Hello,

We are using RabbitMQ output plugins to send values to our brokers.
We want to dynamically set values on headers based on values in the message. But It seems that theses are not parsed as the templatized text is rendered in Rabbit.

- Logstasg Version: 7.5.1 with plugin version 7.0.2. Please find below all available rabbitmq plugins installed :

> [root@ logstash-7.5.1]# bin/logstash-plugin list --verbose | grep rabbit
> OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
> logstash-integration-rabbitmq (7.0.2)
>  ├── logstash-input-rabbitmq
>  └── logstash-output-rabbitmq

- Operating System: RHEL 7.3
- Config File (if you have sensitive info, please remove it):

> output{
>       file { path => "/tmp/logstash-output.log"  }
>       rabbitmq {
>           exchange => "__test_exchange__"
>           exchange_type => "topic"
>           user => "xxxxx"
>           password => "xxxxxx"
>           key => "test"
>           host => "xxxxxxxxxxxx:5672"
>           message_properties => {
>              headers => {
>                   user_id => "%{[id]}"
>                   version => "1.0"
>              }
>           }
>       }
> }

- Sample Data:
{"id" : "367ab74e-252e-11ea-a4b0-fa6b20acc2b4"}

- Steps to Reproduce:
Launch Logstash server and examine output file and RabbitMQ content.

What we expects :  the user_id headers is filled with the value of the iD. Instead, we have the text **%{[id]}** a value.

Please, could someone give some hints on how to achieve this or maybe clarify that it's unimplemented yet ?

Thanks in advance,

**Comment by yaauie** [comment]
A patch adding this functionality was merged in #9 and will be released in version 7.1.0 of this plugin.
