### ISSUE TITLE
Created a PR on the old input repo before I remembered it was bundled into an integration

### ISSUE THREAD

**Issue by geekpete** [logstash-plugins/logstash-integration-rabbitmq#32]
PR is: https://github.com/logstash-plugins/logstash-input-rabbitmq/pull/126

**Comment by yaauie** [comment]
Great! I'll cherry-pick it over.

**Comment by yaauie** [comment]
Your commit is now a part of the in-flight release of 7.1.0 https://github.com/logstash-plugins/logstash-integration-rabbitmq/pull/33/commits
