### ISSUE TITLE
Integrations tests aren't executed on Travis

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-integration-rabbitmq#6]
While testing Travis in my local fork I [created a PR to fail one test](https://github.com/jsvd/logstash-integration-rabbitmq-1/pull/1) on purpose and was surprised CI was still green :)

I understand that running [these tests](https://github.com/logstash-plugins/logstash-integration-rabbitmq/blob/master/spec/inputs/rabbitmq_spec.rb#L132) requires a bit more CI orchestration and these weren't running in the past, just wanted to raise the issue so there are no further surprises :)

**Comment by kares** [comment]
closing this one (resolved since https://github.com/logstash-plugins/logstash-integration-rabbitmq/pull/30) as initially seeing this issue caused some confusion
